// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.188
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Trivial.Ui.Abracadabra
{
    static class Vsix
    {
        public const string Id = "6036efa0-aff4-4699-a68f-dbccadcf39ec";
        public const string Name = "Abracadabra";
        public const string Description = @"Abracadabra";
        public const string Language = "en-US";
        public const string Version = "1.1.0";
        public const string Author = "Greg Trevellick";
        public const string Tags = "abracadabra";
    }
}
