// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.188
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Trivial.Ui.Jeopardy
{
    static class Vsix
    {
        public const string Id = "7ab77a0c-cfb4-4939-9555-853734ea8dac";
        public const string Name = "Jeopardy";
        public const string Description = @"A random Jeopardy trivia question and answer whenever you open a solution.";
        public const string Language = "en-US";
        public const string Version = "1.0.75";
        public const string Author = "Greg Trevellick";
        public const string Tags = "jservice, jeopardy, jservice.io, trivia questions, trivia, quiz";
    }
}
