// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.188
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Trivial.Ui.NumericTrivia
{
    static class Vsix
    {
        public const string Id = "d4b5b8a8-2549-4cd2-9df8-2d469c4da00a";
        public const string Name = "Numeric Trivia";
        public const string Description = @"A random numeral-based trivia fact in a pop-up whenever you open a solution.";
        public const string Language = "en-US";
        public const string Version = "1.0.41";
        public const string Author = "Greg Trevellick";
        public const string Tags = "numbers, trivia, trivial, meaningless, fun, numeral, math";
    }
}
