// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.188
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Trivial.Ui.NumericTrivia
{
    static class Vsix
    {
        public const string Id = "f39b9a5e-80dc-4b2c-9cc1-c015d8ff9840";
        public const string Name = "Numeric Trivia";
        public const string Description = @"A random pop-up numeric fact whenever you open a solution.";
        public const string Language = "en-US";
        public const string Version = "1.0.56";
        public const string Author = "Greg Trevellick";
        public const string Tags = "numbers, trivia, trivial, meaningless, fun, numeral, math";
    }
}
