// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.188
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Trivial.Ui.TrumpQuotes
{
    static class Vsix
    {
        public const string Id = "bffa1350-ab1e-49d9-a8a7-a3f76d92398c";
        public const string Name = "Drain The Swamp";
        public const string Description = @"A random Donald Trump quote in a pop-up whenever you open a solution.";
        public const string Language = "en-US";
        public const string Version = "1.0.1";
        public const string Author = "Greg Trevellick";
        public const string Tags = "tronalddump,  tronald, dump, donald trump, donald, trump, potus, drain, swamp, drain the swamp";
    }
}
