// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.188
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Trivial.Ui.TrumpQuotes
{
    static class Vsix
    {
        public const string Id = "6f3958a5-be00-49a4-b34f-91a70c0db17a";
        public const string Name = "Drain The Swamp";
        public const string Description = @"A random Donald Trump quote in a pop-up whenever you open a solution.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Greg Trevellick";
        public const string Tags = "tronalddump,  tronald, dump, donald trump, donald, trump, potus, drain, swamp, drain the swamp";
    }
}
